name: Elixir CI

on:
  - push
  - pull_request

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-20

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.13' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
      env:
        HLTE_REDIS_URL: 'redis://localhost'
        HLTE_SNS_WHITELIST_JSON: '[]'
    - name: Build prod package
      run: MIX_ENV=prod mix release
    - name: Archive prod build results
      uses: actions/upload-artifact@v2
      with:
        name: prod-build
        path: _build/prod/
